name: "Performance checking with Google Lightouse"
description: "Automated performance checking for web applications"
inputs:
  repo-token:
    description: "Github repo token."
    required: true
  urls:
    description: "List of URLs to audit."
    required: true
  iterations:
    description: "Number of times the check should be run for each page. (Default: 5)"
    required: false
  minimum-desktop-score:
    description: "Threshold tha t the application must meet on desktop devices in order for the build to pass. (Default: 80)"
    required: false
  minimum-mobile-score:
    description: "Threshold that the application must meet on mobile devices in order for the build to pass. (Default: 80)"
    required: false
outputs:
  test:
    description: "test"
runs:
  using: "node12"
  main: "src/main/index.js"
